
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 8.1
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TinggiB = new javax.swing.JTextField();
        PanjangB = new javax.swing.JTextField();
        LebarB = new javax.swing.JTextField();
        btnB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanjangSisi = new javax.swing.JTextField();
        Kubus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        PanjangJariJari = new javax.swing.JTextField();
        Bola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program Penghitung Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 300, 30);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setText("Panjang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 60, 14);

        jLabel3.setText("Lebar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 70, 70, 14);

        jLabel4.setText("Tinggi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 110, 70, 14);
        jPanel1.add(TinggiB);
        TinggiB.setBounds(150, 100, 190, 30);
        jPanel1.add(PanjangB);
        PanjangB.setBounds(150, 20, 190, 30);
        jPanel1.add(LebarB);
        LebarB.setBounds(150, 60, 190, 30);

        btnB.setText("Hitung");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        jPanel1.add(btnB);
        btnB.setBounds(170, 150, 90, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 110, 34, 14);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 30, 30, 14);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 70, 34, 14);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(120, 10, 170, 30);
        jPanel2.add(PanjangSisi);
        PanjangSisi.setBounds(90, 50, 190, 40);

        Kubus.setText("Volume");
        Kubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KubusActionPerformed(evt);
            }
        });
        jPanel2.add(Kubus);
        Kubus.setBounds(150, 110, 67, 23);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(290, 60, 34, 14);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari - Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(110, 10, 170, 30);
        jPanel3.add(PanjangJariJari);
        PanjangJariJari.setBounds(90, 50, 190, 40);

        Bola.setText("Volume");
        Bola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolaActionPerformed(evt);
            }
        });
        jPanel3.add(Bola);
        Bola.setBounds(150, 110, 67, 23);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(290, 60, 34, 14);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 400, 250);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        int panjang, lebar, tinggi;
        panjang  = Integer.parseInt(PanjangB.getText());
        lebar  = Integer.parseInt(LebarB.getText());
        tinggi  = Integer.parseInt(TinggiB.getText());
        int hasil=panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah :"+hasil,"Volume",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBActionPerformed

    private void KubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KubusActionPerformed
        int sisi;
        sisi = Integer.parseInt(PanjangSisi.getText());
        int hasil=sisi*sisi*sisi;
        
        try{
            JOptionPane.showMessageDialog(null, "Volume Kubus Adalah :"+hasil,"Volume",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_KubusActionPerformed

    private void BolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolaActionPerformed
        float jari;
        jari=Integer.parseInt(PanjangJariJari.getText());
        float hasil=(float)(4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null, "Volume Bola Adalah :"+hasil,"Volume",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bola;
    private javax.swing.JButton Kubus;
    private javax.swing.JTextField LebarB;
    private javax.swing.JTextField PanjangB;
    private javax.swing.JTextField PanjangJariJari;
    private javax.swing.JTextField PanjangSisi;
    private javax.swing.JTextField TinggiB;
    private javax.swing.JButton btnB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
